name: ðŸ¤– Dependabot Auto-Merge
on: pull_request

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: merge-${{ github.ref }}
  cancel-in-progress: false

jobs:
  dependabot:
    name: "Enable Auto-Merge âœ…"
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@main

      - name: Enable auto-merge for Dependabot PRs
        run: |
          for i in $(seq 1 5); do
            if gh pr merge --auto --merge "$PR_URL"; then
              break
            elif [ $? -eq 1 ]; then
              sleep $(shuf -i 5-15 -n 1)
            else
              exit 1
            fi
          done
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.PERSONAL_ACCESS_TOKEN}}